### ISSUE TITLE
Meter Serial number - truncating incorrect string

### ISSUE THREAD

**Issue by PawelOstropolski** [emuag/professional_II_lora#1]
Function in decoder for meter serial number should better be done with slice finction as below to extract 2 last characters from the padded string: 
           case 'MeterSerial':
            dataType.value = ('0' + Number(getUint8([data[i++]])).toString(16)).slice(-2);
            dataType.value = ('0' + Number(getUint8([data[i++]])).toString(16)).slice(-2) + dataType.value;
            dataType.value = ('0' + Number(getUint8([data[i++]])).toString(16)).slice(-2) + dataType.value;
            dataType.value = ('0' + Number(getUint8([data[i++]])).toString(16)).slice(-2) + dataType.value;

Current substr(0,2) returns the first 2 characters instead of 2 last characters as intended for leading zero padding in a serial number.

**Comment by fborgo306** [comment]
Hello Pawel,
we appreciate your feedback. I'm going to fix this issue
